### ISSUE TITLE
[FEAT] 온보딩 뷰 짜기

### ISSUE THREAD

**Issue by mdb1217** [mdb1217/Quesookt#7]
## 💡 Issue
온보딩 뷰 짜기

## 📝 todo
- [ ] 닉네임 설정 뷰 짜기
- [ ] 기숙사 테스트 뷰 짜기
- [ ] 기숙사 결과 뷰 짜기
